"""Add ML features to Transaction

Revision ID: f078048e9f7e
Revises: eaa52f5e6f80
Create Date: 2026-01-15 20:07:32.974004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f078048e9f7e'
down_revision: Union[str, Sequence[str], None] = 'eaa52f5e6f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('oldbalanceOrg', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('newbalanceOrig', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('oldbalanceDest', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('newbalanceDest', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'newbalanceDest')
    op.drop_column('transactions', 'oldbalanceDest')
    op.drop_column('transactions', 'newbalanceOrig')
    op.drop_column('transactions', 'oldbalanceOrg')
    # ### end Alembic commands ###
